services:
    web:
        image: nginx:latest
        container_name: web
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html

    app:
        container_name: app
        build:
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/